name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EagleEducation-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          echo Add other actions to build,
          echo test, and deploy your project. #owner longing pannel id and password 
          #contect mobile number 8955683266
          #gmail - bhawanijoshi935@gmail.com 
          #loging id -bhawani120
          #password-8955683266%%
          and password change permission 
          and notes upload video upload and other notification option cantrol in admin 
             admin owner 
          
